version: '3.9'
services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
  nestapp:
    container_name: auth_backend
    build:
      context: ./auth_backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '${API_PORT}:3001'
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
      - JWT_SECRET=${JWT_SECRET}
  reactapp:
    container_name: auth_web_app
    build:
      context: ./auth_web_app
    depends_on:
      - db
      - nestapp
    restart: unless-stopped
    ports:
      - '3000:3000'
volumes:
  pgdata: {}